name: 'Upload Coverage'
description: 'Uploads code coverage reports to codecov with separate flags for separate packages'
runs:
    using: 'composite'
    steps:
        - name: Upload Tagscript Coverage
          uses: codecov/codecov-action@7f8b4b4bde536c465e797be725718b88c5d95e0e # v5
          with:
              files: ./packages/tagscript/coverage/cobertura-coverage.xml
              flags: tagscript

        - name: Upload Tagscript Plugin Discord Coverage
          uses: codecov/codecov-action@7f8b4b4bde536c465e797be725718b88c5d95e0e # v5
          with:
              files: ./packages/tagscript-plugin-discord/coverage/cobertura-coverage.xml
              flags: plugin-discord
