name: 'Upload Coverage'
description: 'Uploads code coverage reports to codecov with separate flags for separate packages'
runs:
    using: 'composite'
    steps:
        - name: Upload Tagscript Coverage
          uses: codecov/codecov-action@6d798873df2b1b8e5846dba6fb86631229fbcb17 # v4
          with:
              files: ./packages/tagscript/coverage/cobertura-coverage.xml
              flags: tagscript

        - name: Upload Tagscript Plugin Discord Coverage
          uses: codecov/codecov-action@6d798873df2b1b8e5846dba6fb86631229fbcb17 # v4
          with:
              files: ./packages/tagscript-plugin-discord/coverage/cobertura-coverage.xml
              flags: plugin-discord
