name: 'Upload Coverage'
description: 'Uploads code coverage reports to codecov with separate flags for separate packages'
runs:
  using: 'composite'
  steps:
    - name: Upload Tagscript Coverage
      uses: codecov/codecov-action@v7
      with:
        files: ./packages/tagscript/coverage/lcov.info
        flags: tagscript

    - name: Upload Tagscript Plugin Discord Coverage
      uses: codecov/codecov-action@v7
      with:
        files: ./packages/tagscript-plugin-discord/coverage/lcov.info
        flags: plugin-discord
