name: 'Upload Coverage'
description: 'Uploads code coverage reports to codecov with separate flags for separate packages'
runs:
    using: 'composite'
    steps:
        - name: Upload Tagscript Coverage
          uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303 # v5
          with:
              files: ./packages/tagscript/coverage/cobertura-coverage.xml
              flags: tagscript

        - name: Upload Tagscript Plugin Discord Coverage
          uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303 # v5
          with:
              files: ./packages/tagscript-plugin-discord/coverage/cobertura-coverage.xml
              flags: plugin-discord
