name: 'Upload Coverage'
description: 'Uploads code coverage reports to codecov with separate flags for separate packages'
runs:
    using: 'composite'
    steps:
        - name: Upload Tagscript Coverage
          uses: codecov/codecov-action@e0b68c6749509c5f83f984dd99a76a1c1a231044 # v4
          with:
              files: ./packages/tagscript/coverage/cobertura-coverage.xml
              flags: tagscript

        - name: Upload Tagscript Plugin Discord Coverage
          uses: codecov/codecov-action@e0b68c6749509c5f83f984dd99a76a1c1a231044 # v4
          with:
              files: ./packages/tagscript-plugin-discord/coverage/cobertura-coverage.xml
              flags: plugin-discord
