name: NPM Auto Deprecate

on:
    schedule:
        - cron: '0 0 * * *'

jobs:
    auto-deprecate:
        name: NPM Auto Deprecate
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
            - name: Use Node.js v18
              uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
              with:
                  node-version: 18
                  cache: yarn
                  registry-url: https://registry.npmjs.org/
            - name: Install Dependencies
              uses: ./scripts/yarnCache
            - name: Build Dependencies
              run: yarn turbo run build --filter=tagscript --no-deps
            - name: Deprecate versions
              run: yarn npm-deprecate
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
