name: NPM Auto Deprecate

on:
    schedule:
        - cron: '0 0 * * *'

jobs:
    auto-deprecate:
        name: NPM Auto Deprecate
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Project
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            - name: Use Node.js v22
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
              with:
                  node-version: 22
                  cache: yarn
                  registry-url: https://registry.npmjs.org/
            - name: Install Dependencies
              uses: ./scripts/yarnCache
            - name: Build Dependencies
              run: yarn turbo run build --filter=tagscript
            - name: Deprecate versions
              run: yarn npm-deprecate
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
