name: 'PR Triage'
on:
    pull_request_target:
jobs:
    pr-triage:
        name: PR Triage
        runs-on: ubuntu-latest
        steps:
            - name: Automatically label PR
              uses: actions/labeler@0967ca812e7fdc8f5f71402a1b486d5bd061fe20 # v4
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  sync-labels: true
