name: 'PR Triage'
on:
    pull_request_target:
jobs:
    pr-triage:
        name: PR Triage
        runs-on: ubuntu-latest
        steps:
            - name: Automatically label PR
              uses: actions/labeler@9fcb2c2f5584144ca754f8bfe8c6f81e77753375 # v4
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  sync-labels: true
