name: 'PR Triage'
on:
    pull_request_target:
jobs:
    pr-triage:
        name: PR Triage
        runs-on: ubuntu-latest
        steps:
            - name: Automatically label PR
              uses: actions/labeler@ba790c862c380240c6d5e7427be5ace9a05c754b # v4
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  sync-labels: true
