name: 'PR Triage'
on:
    pull_request_target:
jobs:
    pr-triage:
        name: PR Triage
        runs-on: ubuntu-latest
        steps:
            - name: Automatically label PR
              uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594 # v4
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  sync-labels: true
