name: Publish

on:
    workflow_dispatch:

jobs:
    PublishPackage:
        name: Publish
        runs-on: ubuntu-latest
        if: github.repository_owner == 'imranbarbhuiya'
        steps:
            - name: Checkout Project
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: main
            - name: Use Node.js v22
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: yarn
                  registry-url: https://registry.yarnpkg.com/
            - name: Install Dependencies
              uses: ./scripts/yarnCache
            - name: Build all packages
              run: yarn build --filter="./packages/*"
            - name: Configure Git
              run: |
                  git remote set-url origin "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git"
                  git config --local user.email "${GITHUB_EMAIL}"
                  git config --local user.name "${GITHUB_USER}"
              env:
                  GITHUB_USER: github-actions[bot]
                  GITHUB_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Bump Versions and make release
              run: yarn bump
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Publish to NPM
              run: |
                  yarn config set npmAuthToken ${NODE_AUTH_TOKEN}
                  yarn config set npmPublishRegistry "https://registry.yarnpkg.com"
                   for d in packages/*; do
                    pushd $d
                    yarn bump
                    yarn npm publish
                    popd
                  done
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
                  NPM_CONFIG_PROVENANCE: true
